clusterInfrastructure:
  provider: kind
clusterPackages:
  kapp-controller:
    enabled: true
websiteStyling:
  trainingPortal:
    style: |
      .navbar.bg-dark {
        background-color: #8e83e4 !important;
      }
